# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: cluster-auto-mode
    region: us-east-1
    version: '1.32'
    tags:
      auto-mode: "enabled"
      graviton-enabled: "true"
      spot-instances-enabled: "true"
      cost-optimization: "enabled"
      architecture: "multi-arch"
      environment: "dev"
      owner: "devops-team"
      provisioned-by: "eksctl"


availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]    

vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true    

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    logRetentionInDays: 1

autoModeConfig:
    enabled: true
    nodePools: 
      - general-purpose
      - system    

iam:
  withOIDC: true


